name: Build and Push Frps

on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: frps
          tags: raymond17/frps:latest
          push: true
      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: frps
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: ghcr.io/OWNER/IMAGE-NAME
      #     repository: raymondtc/frps
      #     tag_with_ref: true